volumes:
  data:

services:
  mariadb:
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=mariadbpw
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
  myapp:
    image: [YOUR-APP-IMAGE]