version: '3.3'

services:
  mariadb:
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=mariadbpw
      - MYSQL_DATABASE=quizzme
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
    networks:
      - base_network

  api:
    image: node:latest
    networks:
      - base_network
    depends_on:
      - mariadb
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "npm run start:dev"

networks:
  base_network:


volumes:
  data:
